#!/usr/bin/env python
#
# Copyright(C) 2011 Simon Howard
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

# statchecker regression testing script.
#
# This script examines the zip files in the Compet-N tree, extracts
# the demos and plays them back using the configured source port.
# Statistics information is logged to a file using the -statdump
# parameter and the output is compared with the reference version
# for Vanilla Doom. A summary is outputted of the demos that pass
# or fail this test.

import os
import sys
from common import *
from config import *

GREEN = '\033[92m'
RED = '\033[91m'
COLOR_END = '\033[0m'

OUTPUT_FILENAME = "out.txt"

def read_file(filename):
	result = []

	stream = open(filename)
	lines = stream.readlines()
	stream.close()

	lines = map(lambda x: x.strip(), lines)

	return "\n".join(lines)

def check_output(zipfile_path, lmpname):
	expected_file = os.path.join("output", zipfile_path,
	                             lmpname.lower().replace(".lmp", ".txt"))

	output = read_file(OUTPUT_FILENAME)
	expected = read_file(expected_file)

	if output != expected:
		os.system("diff -u %s %s" % (expected_file, OUTPUT_FILENAME))

	return output == expected

def print_result(zipfile_path, lmpname, success):

	if success:
		success_string = GREEN + " OK " + COLOR_END
	else:
		success_string = RED + "FAIL" + COLOR_END

	print "%-50s%-15s%s" % (zipfile_path, lmpname, success_string)
	sys.stdout.flush()

# Run the specified demo and check the output is correct.

def process_lmp(gametype, zipfile_path, zf, lmpname):
	global passed, failed

	gamepath, exe = GAME_PATHS[gametype]
	iwad = os.path.join(gamepath, "%s.wad" % gametype)

	try:
		zf.extract(lmpname)

		if os.path.exists(OUTPUT_FILENAME):
			os.remove(OUTPUT_FILENAME)

		cmd = "%s %s" % (PORT_EXE, PORT_OPTIONS)
		cmd += " -iwad %s" % iwad
		cmd += " -timedemo %s" % lmpname
		cmd += " -statdump %s" % OUTPUT_FILENAME

		#print cmd
		os.system(cmd + ">/dev/null 2>/dev/null")

		relpath = os.path.relpath(zipfile_path, COMPETN_PATH)

		success = check_output(relpath, lmpname)

		print_result(relpath, lmpname, success)

		if success:
			passed += 1
		else:
			failed += 1
	finally:
		if os.path.exists(lmpname):
			os.remove(lmpname)
		if os.path.exists(OUTPUT_FILENAME):
			os.remove(OUTPUT_FILENAME)

passed, failed = 0, 0

process_all_zips(COMPETN_PATH, process_lmp)

print "%i demo(s) passed, %i demo(s) failed." % (passed, failed)

